name: Docker Build and Publish and Deploy to DeployAja

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  REGISTRY: ghcr.io/lukluk/demo-deployaja
  IMAGE_NAME: demo-deployaja
  DOCKER_BUILDKIT: 1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} 

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: DeployAja Plan
        uses: deployaja/deployaja-cli@1.0.3
        with:
          command: plan
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
      - name: DeployAja Deploy
        uses: deployaja/deployaja-cli@1.0.3
        with:
          command: deploy
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
          additional-args: --set container.image=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ github.sha }} 
      - name: DeployAja Status
        uses: deployaja/deployaja-cli@1.0.3
        with:
          command: status
          api-token: ${{ secrets.DEPLOYAJA_TOKEN }}
          
        
